// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfnqahkwjtnoiydosnhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmbnFhaGt3anRub2l5ZG9zbmhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTQyNDgsImV4cCI6MjA2MzkzMDI0OH0.Uo2ybuRxf7AsjAIcbwidq2Fuktyjh4sLgB14Wx6wTSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);